import type { SettingDef } from "./settings-schema-types";

/** Web Content and Browsing settings */
export const WEB_SETTINGS: SettingDef[] = [
  // ── Web Content ─────────────────────────────────────────────────────────
  {
    key: "startUrl",
    label: "Start URL",
    description: "Home URL. Multiple URLs (one per line) open on separate tabs.",
    type: "multiline",
    category: "Web Content",
  },
  {
    key: "urlUsername",
    label: "HTTP Auth Username",
    description: "Username for Basic HTTP authentication on the Start URL host.",
    type: "string",
    category: "Web Content",
  },
  {
    key: "urlPassword",
    label: "HTTP Auth Password",
    description: "Password for Basic HTTP authentication on the Start URL host.",
    type: "password",
    category: "Web Content",
  },
  {
    key: "enableFullscreen",
    label: "Enable Fullscreen Videos",
    description: "Allow videos to be switched to fullscreen.",
    type: "boolean",
    category: "Web Content",
  },
  {
    key: "autoplayVideos",
    label: "Autoplay Videos",
    description: "Autoplay embedded HTML5 videos on page load.",
    type: "boolean",
    category: "Web Content",
  },
  {
    key: "autoplayAudio",
    label: "Autoplay Audio",
    description: "Autoplay embedded HTML5 audio on page load.",
    type: "boolean",
    category: "Web Content",
  },
  {
    key: "enableFileUpload",
    label: "Enable File Upload",
    description: "Allow users to upload files to web forms.",
    type: "boolean",
    category: "Web Content",
    plusOnly: true,
  },
  {
    key: "enableJavascriptAlerts",
    label: "Enable JavaScript Alerts",
    description: "Allow JavaScript alert, prompt, and confirm dialogs.",
    type: "boolean",
    category: "Web Content",
  },
  {
    key: "enablePopups",
    label: "Enable Popups",
    description: "Support popups and open links in new frames.",
    type: "boolean",
    category: "Web Content",
    plusOnly: true,
  },
  {
    key: "enableWebcam",
    label: "Enable Webcam Access",
    description: "Allow websites to access the webcam via HTML5 (HTTPS only).",
    type: "boolean",
    category: "Web Content",
    plusOnly: true,
  },
  {
    key: "enableMicrophone",
    label: "Enable Microphone Access",
    description: "Allow websites to access the microphone via HTML5 (HTTPS only).",
    type: "boolean",
    category: "Web Content",
    plusOnly: true,
  },
  {
    key: "enableGeolocation",
    label: "Enable Geolocation Access",
    description: "Allow websites to access device location via HTML5 (HTTPS only).",
    type: "boolean",
    category: "Web Content",
    plusOnly: true,
  },
  {
    key: "urlWhitelist",
    label: "URL Whitelist",
    description: "One URL per line. Use * as wildcard. All URLs allowed if empty.",
    type: "multiline",
    category: "Web Content",
  },
  {
    key: "urlBlacklist",
    label: "URL Blacklist",
    description: "One URL per line. Use * as wildcard. Overrides whitelist.",
    type: "multiline",
    category: "Web Content",
  },
  {
    key: "redirectBlockedToStartUrl",
    label: "Redirect Blocked URLs to Start URL",
    description: "Redirect URLs blocked by whitelist or blacklist to the Start URL.",
    type: "boolean",
    category: "Web Content",
  },
  {
    key: "customErrorUrl",
    label: "Custom Error URL",
    description: "Page to load on any error. Use fully://errorpage for a built-in page.",
    type: "url",
    category: "Web Content",
  },
  {
    key: "userAgent",
    label: "Fake User Agent",
    description: "Pretend to be a different browser to some websites.",
    type: "select",
    options: [
      { value: "default", label: "Default (Android)" },
      { value: "chrome", label: "Google Chrome" },
      { value: "edge", label: "Microsoft Edge" },
      { value: "firefox", label: "Mozilla Firefox" },
      { value: "safari", label: "Apple Safari" },
      { value: "custom", label: "Custom (see Custom User Agent)" },
    ],
    category: "Web Content",
  },
  {
    key: "customUserAgent",
    label: "Custom User Agent String",
    description: "Arbitrary UA string. Only used when Fake User Agent is set to Custom.",
    type: "string",
    category: "Web Content",
    plusOnly: true,
  },
  {
    key: "injectJavascript",
    label: "Inject JavaScript",
    description: "JavaScript code to run after every page load.",
    type: "multiline",
    category: "Web Content",
    plusOnly: true,
  },

  // ── Browsing ─────────────────────────────────────────────────────────────
  {
    key: "enableBackButton",
    label: "Enable Back Button",
    description: "Go back in history when the device back button is tapped.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "enablePullToRefresh",
    label: "Enable Pull to Refresh",
    description: "Allow a downward pull gesture to reload the current page.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "enableTapSound",
    label: "Enable Tap Sound",
    description: "Play a click sound when the user taps in the web view.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "waitForNetwork",
    label: "Wait for Network Connection",
    description: "Never try to load a page if no network connection is available.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "autoReloadOnIdle",
    label: "Auto Reload on Idle (seconds)",
    description: "Reload after this many seconds of user inactivity. 0 = disabled.",
    type: "number",
    min: 0,
    category: "Browsing",
  },
  {
    key: "autoReloadOnError",
    label: "Auto Reload after Page Error (seconds)",
    description: "Reload after this many seconds on a page load failure. 0 = disabled.",
    type: "number",
    min: 0,
    category: "Browsing",
  },
  {
    key: "autoReloadOnScreenOn",
    label: "Auto Reload on Screen On",
    description: "Reload the page automatically when the screen turns on.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "autoReloadOnScreensaverStop",
    label: "Auto Reload on Screensaver Stop",
    description: "Reload when the screensaver stops.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "autoReloadOnNetworkReconnect",
    label: "Auto Reload on Network Reconnect",
    description: "Reload when WiFi/LAN/LTE reconnects.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "autoReloadOnInternetReconnect",
    label: "Auto Reload on Internet Reconnect",
    description: "Reload Start URL when real Internet connection reappears.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "clearCacheOnReload",
    label: "Clear Cache on Auto Reload",
    description: "Purge the browser cache before each auto reload.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "clearCookiesOnReload",
    label: "Clear Cookies on Auto Reload",
    description: "Delete cookies before each auto reload.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "clearWebstorageOnReload",
    label: "Clear Web Storage on Auto Reload",
    description: "Clear localStorage/sessionStorage before each auto reload.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "loadCurrentOnReload",
    label: "Reload Current Page (not Start URL)",
    description: "Auto reload reloads the current page instead of the Start URL.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "enableZoom",
    label: "Enable Zoom",
    description: "Allow pinch-to-zoom on web pages that support it.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "loadInOverviewMode",
    label: "Load in Overview Mode",
    description: "Scale the page to fit the device width on load.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "initialScale",
    label: "Initial Scale (%)",
    description: "Initial zoom level in percent. Ignored if Use Wide Viewport is on.",
    type: "number",
    min: 10,
    max: 500,
    category: "Browsing",
  },
  {
    key: "fontScale",
    label: "Font Size Scale (%)",
    description: "Font scaling in percent. Default: 100.",
    type: "number",
    min: 10,
    max: 300,
    category: "Browsing",
  },
  {
    key: "viewInDesktopMode",
    label: "View in Desktop Mode",
    description: "Request desktop layout from websites instead of mobile.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "enableThirdPartyCookies",
    label: "Enable Third-Party Cookies",
    description: "Allow accepting cookies from third-party domains.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "enableUserInteraction",
    label: "Enable User Interaction",
    description: "Allow any user interaction in the web view.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "enableScrolling",
    label: "Enable Page Scrolling",
    description: "Allow scrolling in the web view.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "enableDragging",
    label: "Enable Dragging",
    description: "Allow dragging objects by touch. Disabling also disables scrolling.",
    type: "boolean",
    category: "Browsing",
  },
  {
    key: "enableLongTap",
    label: "Enable Long Tap",
    description: "Allow long-tap actions like text selection and context menus.",
    type: "boolean",
    category: "Browsing",
  },
];
