import type { SettingDef } from "./settings-schema-types";

/** Kiosk Mode and Security settings */
export const KIOSK_SETTINGS: SettingDef[] = [
  // ── Kiosk Mode ───────────────────────────────────────────────────────────
  {
    key: "kioskMode",
    label: "Enable Kiosk Mode",
    description: "Lock down the device with an exit gesture and PIN.",
    type: "boolean",
    category: "Kiosk Mode",
    plusOnly: true,
  },
  {
    key: "kioskExitGesture",
    label: "Kiosk Exit Gesture",
    description: "Gesture required to show the PIN dialog.",
    type: "select",
    options: [
      { value: "0", label: "Swipe from Left" },
      { value: "1", label: "5 Fast Taps (Fully only)" },
      { value: "2", label: "7 Fast Taps (any app)" },
      { value: "3", label: "Double-tap Top-Left + Bottom-Right" },
    ],
    category: "Kiosk Mode",
  },
  {
    key: "kioskPassword",
    label: "Kiosk PIN",
    description: "PIN required to exit Kiosk Mode. Leave empty to skip the PIN dialog.",
    type: "password",
    category: "Kiosk Mode",
  },
  {
    key: "wifiPassword",
    label: "Wifi / Settings PIN",
    description: "Separate PIN that grants access to Wifi or other Android settings only.",
    type: "password",
    category: "Kiosk Mode",
  },
  {
    key: "disableStatusBar",
    label: "Disable Status Bar",
    description: "Lock the status bar and block access to system settings.",
    type: "boolean",
    category: "Kiosk Mode",
  },
  {
    key: "disableVolumeButtons",
    label: "Disable Volume Buttons",
    description: "Restrict volume buttons in Kiosk Mode.",
    type: "boolean",
    category: "Kiosk Mode",
  },
  {
    key: "limitVolumeLevel",
    label: "Limit Max Volume (%)",
    description: "Maximum volume level on all channels (0–100). Empty = disabled.",
    type: "number",
    min: 0,
    max: 100,
    category: "Kiosk Mode",
  },
  {
    key: "disablePowerButton",
    label: "Disable Power Button",
    description: "Make the power button mostly non-functional in Kiosk Mode.",
    type: "boolean",
    category: "Kiosk Mode",
  },
  {
    key: "disableHomeButton",
    label: "Disable Home Button",
    description: "Lock the home button and set Fully as the default launcher.",
    type: "boolean",
    category: "Kiosk Mode",
  },
  {
    key: "disableContextMenus",
    label: "Disable Context Menus",
    description: "Disable system context menus (Copy/Share/Select all) in Fully.",
    type: "boolean",
    category: "Kiosk Mode",
  },
  {
    key: "disableOtherApps",
    label: "Disable Other Apps",
    description: "Block all other apps except those intentionally started from Fully.",
    type: "boolean",
    category: "Kiosk Mode",
  },
  {
    key: "advancedKioskProtection",
    label: "Advanced Kiosk Protection",
    description: "Enable advanced protection against starting other apps.",
    type: "boolean",
    category: "Kiosk Mode",
  },
  {
    key: "appWhitelist",
    label: "App Whitelist",
    description: "Packages allowed to go to foreground. One package or component per line. Use * wildcard.",
    type: "multiline",
    category: "Kiosk Mode",
  },
  {
    key: "appBlacklist",
    label: "App Blacklist",
    description: "Packages always blocked. One package or component per line. Use * wildcard.",
    type: "multiline",
    category: "Kiosk Mode",
  },
  {
    key: "disableNotifications",
    label: "Disable Notifications",
    description: "Block all status bar notifications from other apps.",
    type: "boolean",
    category: "Kiosk Mode",
  },
  {
    key: "disableIncomingCalls",
    label: "Disable Incoming Calls",
    description: "Block all incoming phone calls.",
    type: "boolean",
    category: "Kiosk Mode",
  },
  {
    key: "disableOutgoingCalls",
    label: "Disable Outgoing Calls",
    description: "Block all outgoing calls (except emergency calls).",
    type: "boolean",
    category: "Kiosk Mode",
  },
  {
    key: "disableCamera",
    label: "Disable Camera",
    description: "Disable the camera for all apps (also disables Visual Motion Detection).",
    type: "boolean",
    category: "Kiosk Mode",
  },
  {
    key: "disableScreenshots",
    label: "Disable Screenshots",
    description: "Disallow screenshots and screen recording in Fully. App restart required to apply.",
    type: "boolean",
    category: "Kiosk Mode",
  },

  // ── Security ─────────────────────────────────────────────────────────────
  {
    key: "enableJavascriptInterface",
    label: "Enable JavaScript Interface",
    description: "Allow websites to use Fully's JS API to access device features. Only enable if you trust all loaded sites.",
    type: "boolean",
    category: "Security",
    plusOnly: true,
    securityWarning: true,
  },
  {
    key: "localhostFileAccess",
    label: "Localhost File Access",
    description: "Access local files via https://localhost/…. Potentially insecure — any site can read local files.",
    type: "boolean",
    category: "Security",
    plusOnly: true,
    securityWarning: true,
  },
  {
    key: "ignoreSSLErrors",
    label: "Ignore SSL Errors",
    description: "Ignore TLS certificate errors. Makes HTTPS connections completely unsafe.",
    type: "boolean",
    category: "Security",
    securityWarning: true,
  },
  {
    key: "enableSafeBrowsing",
    label: "Enable Safe Browsing",
    description: "Block sites Google has classified as threats. Requires Android 8.1+.",
    type: "boolean",
    category: "Security",
  },
  {
    key: "enableWebFilter",
    label: "Enable Web Filter (Ad Blocker)",
    description: "Block hosts listed in fully-blackhosts.txt on device storage.",
    type: "boolean",
    category: "Security",
    plusOnly: true,
  },
  {
    key: "enableDRM",
    label: "Enable DRM Protected Content",
    description: "Enable DRM-protected content in the web view (experimental).",
    type: "boolean",
    category: "Security",
  },
  {
    key: "pauseWebviewInBackground",
    label: "Pause Webview in Background",
    description: "Pause the web view when Fully is in the background or screen is off (experimental).",
    type: "boolean",
    category: "Security",
  },
  {
    key: "lockSafeMode",
    label: "Lock Safe Mode",
    description: "Prevent booting into Android safe mode using the Kiosk PIN.",
    type: "boolean",
    category: "Security",
  },
  {
    key: "enableRootFeatures",
    label: "Enable Root Features",
    description: "Grant root privileges to the app. Rooted devices only.",
    type: "boolean",
    category: "Security",
    plusOnly: true,
    securityWarning: true,
  },
];
