import type { SettingDef } from "./settings-schema-types";

/** Screen & Display, Audio & Media, Motion Detection, Screensaver,
 *  Remote & MQTT, App Management, and Other settings */
export const DEVICE_SETTINGS: SettingDef[] = [
  // ── Screen & Display ──────────────────────────────────────────────────────
  {
    key: "keepScreenOn",
    label: "Keep Screen On",
    description: "Prevent the device from going to sleep via Android display settings.",
    type: "boolean",
    category: "Screen & Display",
  },
  {
    key: "keepScreenOnAdvanced",
    label: "Keep Screen On (Advanced)",
    description: "Use this if the standard option fails with Android 10+ devices.",
    type: "boolean",
    category: "Screen & Display",
  },
  {
    key: "screenBrightness",
    label: "Screen Brightness",
    description: "Brightness level (0–255). Leave empty for system default.",
    type: "number",
    min: 0,
    max: 255,
    category: "Screen & Display",
  },
  {
    key: "screenOffTimer",
    label: "Screen Off Timer (seconds)",
    description: "Turn the screen off after this many seconds of inactivity. 0 = disabled.",
    type: "number",
    min: 0,
    category: "Screen & Display",
    plusOnly: true,
  },
  {
    key: "screenOrientation",
    label: "Force Screen Orientation",
    description: "Force a specific screen orientation for Fully (not other apps).",
    type: "select",
    options: [
      { value: "0", label: "Auto (system default)" },
      { value: "1", label: "Portrait" },
      { value: "2", label: "Landscape" },
      { value: "3", label: "Reverse Portrait" },
      { value: "4", label: "Reverse Landscape" },
    ],
    category: "Screen & Display",
  },
  {
    key: "unlockScreen",
    label: "Show Above Lock Screen",
    description: "Show Fully above the Android lock screen.",
    type: "boolean",
    category: "Screen & Display",
  },
  {
    key: "launchOnBoot",
    label: "Launch on Boot",
    description: "Start Fully automatically when the device boots.",
    type: "boolean",
    category: "Screen & Display",
  },
  {
    key: "showNavigationBar",
    label: "Show Navigation Bar",
    description: "Show the system navigation bar permanently.",
    type: "boolean",
    category: "Screen & Display",
  },
  {
    key: "navigationBarColor",
    label: "Navigation Bar Color",
    description: "Background color for the navigation bar (ARGB hex).",
    type: "color",
    category: "Screen & Display",
  },
  {
    key: "showStatusBar",
    label: "Show Status Bar",
    description: "Show the system status bar permanently.",
    type: "boolean",
    category: "Screen & Display",
  },
  {
    key: "statusBarColor",
    label: "Status Bar Color",
    description: "Background color for the status bar (ARGB hex).",
    type: "color",
    category: "Screen & Display",
  },
  {
    key: "showActionBar",
    label: "Show Action Bar",
    description: "Show the action bar with navigation buttons.",
    type: "boolean",
    category: "Screen & Display",
  },
  {
    key: "actionBarTitle",
    label: "Action Bar Title",
    description: "Text shown on the action bar. Supports $mac, $deviceName, $ip4 etc.",
    type: "string",
    category: "Screen & Display",
  },
  {
    key: "actionBarColor",
    label: "Action Bar Background Color",
    type: "color",
    category: "Screen & Display",
  },
  {
    key: "actionBarTextColor",
    label: "Action Bar Text / Icon Color",
    type: "color",
    category: "Screen & Display",
  },
  {
    key: "showTabs",
    label: "Show Browser Tabs",
    description: "Show tab bar when multiple Start URLs are loaded.",
    type: "boolean",
    category: "Screen & Display",
  },
  {
    key: "showAddressBar",
    label: "Show Address Bar",
    description: "Show the address bar with the current URL.",
    type: "boolean",
    category: "Screen & Display",
  },
  {
    key: "showProgressBar",
    label: "Show Progress Bar",
    description: "Show a loading progress bar at the top of the screen.",
    type: "boolean",
    category: "Screen & Display",
  },
  {
    key: "progressBarColor",
    label: "Progress Bar Color",
    type: "color",
    category: "Screen & Display",
  },
  {
    key: "wifiMode",
    label: "WiFi Mode on Start",
    description: "Force enable or disable WiFi when Fully starts.",
    type: "select",
    options: [
      { value: "0", label: "No change" },
      { value: "1", label: "Enable" },
      { value: "2", label: "Disable" },
    ],
    category: "Screen & Display",
  },
  {
    key: "bluetoothMode",
    label: "Bluetooth Mode on Start",
    description: "Force enable or disable Bluetooth when Fully starts.",
    type: "select",
    options: [
      { value: "0", label: "No change" },
      { value: "1", label: "Enable" },
      { value: "2", label: "Disable" },
    ],
    category: "Screen & Display",
  },
  {
    key: "deviceName",
    label: "Device Name",
    description: "Set the Bluetooth/device name. Supports placeholders like $mac.",
    type: "string",
    category: "Screen & Display",
  },

  // ── Audio & Media ─────────────────────────────────────────────────────────
  {
    key: "soundVolume",
    label: "Sound Volume (0–100)",
    description: "Default sound volume percentage.",
    type: "number",
    min: 0,
    max: 100,
    category: "Audio & Media",
  },
  {
    key: "volumeLevels",
    label: "Set Volume Levels on Start",
    description: "Comma-separated stream:percent list, e.g. 3:80,4:50. Empty = no change.",
    type: "string",
    category: "Audio & Media",
    plusOnly: true,
  },
  {
    key: "ttsLocale",
    label: "TTS Default Locale",
    description: "Default locale for Text-to-Speech, e.g. en-US.",
    type: "string",
    category: "Audio & Media",
  },
  {
    key: "ttsEngine",
    label: "TTS Engine Package",
    description: "Package name of the TTS engine to use. Leave empty for system default.",
    type: "string",
    category: "Audio & Media",
  },
  {
    key: "videoPlayerEngine",
    label: "Video Player Engine",
    description: "Engine used to play fullscreen videos. App restart required.",
    type: "select",
    options: [
      { value: "0", label: "Android Media Player (default)" },
      { value: "1", label: "Media3 Exoplayer (Android 7+)" },
    ],
    category: "Audio & Media",
  },
  {
    key: "resumePlaybackOnForeground",
    label: "Resume Playback on Foreground",
    description: "Try to resume video/audio when Fully returns to foreground.",
    type: "boolean",
    category: "Audio & Media",
  },
  {
    key: "redirectAudioToEarpiece",
    label: "Redirect Audio to Earpiece",
    description: "Redirect audio output to the phone earpiece.",
    type: "boolean",
    category: "Audio & Media",
    plusOnly: true,
  },

  // ── Motion Detection ──────────────────────────────────────────────────────
  {
    key: "motionDetection",
    label: "Enable Visual Motion Detection",
    description: "Use the front camera to detect motion.",
    type: "boolean",
    category: "Motion Detection",
    plusOnly: true,
  },
  {
    key: "motionSensitivity",
    label: "Detector Sensitivity (0–100)",
    description: "Higher value = more sensitive. Best results around 90–95.",
    type: "number",
    min: 0,
    max: 100,
    category: "Motion Detection",
  },
  {
    key: "motionFrameRate",
    label: "Detector Frame Rate (1–25)",
    description: "Detection samples per second. Higher = more reliable but more CPU.",
    type: "number",
    min: 1,
    max: 25,
    category: "Motion Detection",
  },
  {
    key: "darknessLevel",
    label: "Darkness Level (0–100)",
    description: "Threshold for darkness detection. Lower triggers at lower ambient light.",
    type: "number",
    min: 0,
    max: 100,
    category: "Motion Detection",
  },
  {
    key: "showCamPreview",
    label: "Show Cam Preview",
    description: "Show a small camera preview in the bottom-right corner.",
    type: "boolean",
    category: "Motion Detection",
  },
  {
    key: "detectFaces",
    label: "Detect Faces",
    description: "Enable face detection on the camera image.",
    type: "boolean",
    category: "Motion Detection",
  },
  {
    key: "turnScreenOnOnMotion",
    label: "Turn Screen On on Motion",
    description: "Wake the screen when motion is detected.",
    type: "boolean",
    category: "Motion Detection",
  },
  {
    key: "exitScreensaverOnMotion",
    label: "Exit Screensaver on Motion",
    description: "Stop the screensaver when motion is detected.",
    type: "boolean",
    category: "Motion Detection",
  },
  {
    key: "turnScreenOffInDarkness",
    label: "Turn Screen Off in Darkness",
    description: "Turn the screen off when the camera detects complete darkness.",
    type: "boolean",
    category: "Motion Detection",
  },
  {
    key: "acousticMotionDetection",
    label: "Enable Acoustic Motion Detection",
    description: "Use the device microphone to detect motion sounds.",
    type: "boolean",
    category: "Motion Detection",
    plusOnly: true,
  },
  {
    key: "acousticSensitivity",
    label: "Acoustic Sensitivity (0–100)",
    description: "Microphone sensitivity for acoustic motion detection.",
    type: "number",
    min: 0,
    max: 100,
    category: "Motion Detection",
  },

  // ── Screensaver ───────────────────────────────────────────────────────────
  {
    key: "screensaverTimer",
    label: "Screensaver Timer (seconds)",
    description: "Start screensaver after this many seconds of inactivity. 0 = disabled.",
    type: "number",
    min: 0,
    category: "Screensaver",
    plusOnly: true,
  },
  {
    key: "screensaverBrightness",
    label: "Screensaver Brightness (0–255)",
    description: "Screen brightness during screensaver. Empty = default.",
    type: "number",
    min: 0,
    max: 255,
    category: "Screensaver",
  },
  {
    key: "screensaverWallpaper",
    label: "Screensaver Wallpaper URL",
    description: "Website shown as screensaver background. Use fully://color#000000 for solid black.",
    type: "url",
    category: "Screensaver",
  },
  {
    key: "screensaverFadeDuration",
    label: "Fade In/Out Duration (ms)",
    description: "Image fading duration in milliseconds. Default: 200.",
    type: "number",
    min: 0,
    category: "Screensaver",
  },
  {
    key: "useAndroidScreensaver",
    label: "Use Android Screen Saver (Daydream)",
    description: "Start the Android Screen Saver instead of Fully's screensaver.",
    type: "boolean",
    category: "Screensaver",
  },

  // ── Remote & MQTT ─────────────────────────────────────────────────────────
  {
    key: "remoteAdmin",
    label: "Enable Remote Administration",
    description: "Allow remote management and the REST API interface.",
    type: "boolean",
    category: "Remote & MQTT",
    plusOnly: true,
  },
  {
    key: "remoteAdminPassword",
    label: "Remote Admin Password",
    description: "Password required for Remote Admin and the REST API.",
    type: "password",
    category: "Remote & MQTT",
  },
  {
    key: "remoteAdminLocalNetwork",
    label: "Remote Admin from Local Network",
    description: "Accept connections at http://device-ip:2323.",
    type: "boolean",
    category: "Remote & MQTT",
  },
  {
    key: "remoteAdminFileManagement",
    label: "Enable File Management on Remote Admin",
    description: "Allow listing and downloading local files via Remote Admin.",
    type: "boolean",
    category: "Remote & MQTT",
  },
  {
    key: "remoteAdminScreenshot",
    label: "Enable Screenshot on Remote Admin",
    description: "Allow taking screenshots via Remote Admin.",
    type: "boolean",
    category: "Remote & MQTT",
  },
  {
    key: "remoteAdminCamshot",
    label: "Enable Camshot on Remote Admin",
    description: "Allow taking camera snapshots via Remote Admin (requires Motion Detection).",
    type: "boolean",
    category: "Remote & MQTT",
  },
  {
    key: "mqttEnabled",
    label: "Enable MQTT",
    description: "Publish device info and events to an MQTT broker.",
    type: "boolean",
    category: "Remote & MQTT",
    plusOnly: true,
  },
  {
    key: "mqttBrokerUrl",
    label: "MQTT Broker URL",
    description: "e.g. ssl://broker.example.com:8883 or tcp://192.168.1.10:1883",
    type: "url",
    category: "Remote & MQTT",
  },
  {
    key: "mqttBrokerUsername",
    label: "MQTT Username",
    type: "string",
    category: "Remote & MQTT",
  },
  {
    key: "mqttBrokerPassword",
    label: "MQTT Password",
    type: "password",
    category: "Remote & MQTT",
  },
  {
    key: "mqttClientId",
    label: "MQTT Client ID",
    description: "Optional. Supports $deviceId placeholder. Random ID used if empty.",
    type: "string",
    category: "Remote & MQTT",
  },
  {
    key: "mqttDeviceInfoTopic",
    label: "MQTT Device Info Topic",
    description: "Default: $appId/deviceInfo/$deviceId",
    type: "string",
    category: "Remote & MQTT",
  },
  {
    key: "mqttEventTopic",
    label: "MQTT Event Topic",
    description: "Default: $appId/event/$event/$deviceId",
    type: "string",
    category: "Remote & MQTT",
  },

  // ── App Management ────────────────────────────────────────────────────────
  {
    key: "dailyUsageStats",
    label: "Daily Usage Statistics",
    description: "Gather usage stats locally on the device.",
    type: "boolean",
    category: "App Management",
    plusOnly: true,
  },
  {
    key: "restartOnCrash",
    label: "Restart Fully After Crash",
    description: "Automatically restart the app after any crash.",
    type: "boolean",
    category: "App Management",
    plusOnly: true,
  },
  {
    key: "restartOnUpdate",
    label: "Restart Fully After Update",
    description: "Restart after updating Fully or Android System WebView.",
    type: "boolean",
    category: "App Management",
    plusOnly: true,
  },
  {
    key: "runAsPriorityApp",
    label: "Run as Priority App",
    description: "Prevent Android from killing Fully when resources are low.",
    type: "boolean",
    category: "App Management",
  },
  {
    key: "regainFocusTimer",
    label: "Regain Focus Timer (seconds)",
    description: "Bring Fully to the foreground after this many idle seconds. 0 = disabled.",
    type: "number",
    min: 0,
    category: "App Management",
    plusOnly: true,
  },
  {
    key: "loadZipUrl",
    label: "Load Content from ZIP File URL",
    description: "Download and unpack a ZIP file to local storage. Checked hourly for updates.",
    type: "url",
    category: "App Management",
    plusOnly: true,
  },
  {
    key: "apkFilesToInstall",
    label: "APK Files to Install",
    description: "One APK URL per line. Silently installed on provisioned devices (Android 6+).",
    type: "multiline",
    category: "App Management",
  },
  {
    key: "apkUpdateInterval",
    label: "APK Update Check Interval (minutes)",
    description: "Check APK URLs for updates this often. Minimum 15.",
    type: "number",
    min: 15,
    category: "App Management",
  },
  {
    key: "customLocale",
    label: "Custom Locale",
    description: "Force a locale in the web view, e.g. en-US or de-CH.",
    type: "string",
    category: "App Management",
    plusOnly: true,
  },

  // ── Other ─────────────────────────────────────────────────────────────────
  {
    key: "enableVersionInfo",
    label: "Show Version Info on Start",
    description: "Display update summaries when Fully starts.",
    type: "boolean",
    category: "Other",
  },
  {
    key: "darkMode",
    label: "Dark Mode",
    description: "Dark mode handling in the app. Requires app restart to apply.",
    type: "select",
    options: [
      { value: "0", label: "Follow System" },
      { value: "1", label: "Always Light" },
      { value: "2", label: "Always Dark" },
    ],
    category: "Other",
  },
  {
    key: "renderInCutoutArea",
    label: "Render in Notch / Cutout Area",
    description: "Show content in the device notch area.",
    type: "boolean",
    category: "Other",
  },
  {
    key: "confirmExit",
    label: "Confirm Exit",
    description: "Show a confirmation dialog when closing Fully.",
    type: "boolean",
    category: "Other",
  },
  {
    key: "customTextVariable",
    label: "Custom Text Variable",
    description: "Value accessible as $customVariable in all URL settings.",
    type: "string",
    category: "Other",
  },
  {
    key: "enableEnvironmentSensors",
    label: "Enable Environment Sensors",
    description: "Enable reading available environment sensors (temperature, light, etc.).",
    type: "boolean",
    category: "Other",
    plusOnly: true,
  },
  {
    key: "enableBarcodeScannerIntegration",
    label: "Barcode Scanner Integration",
    description: "Enable integration with an external barcode scanner app.",
    type: "boolean",
    category: "Other",
    plusOnly: true,
  },
  {
    key: "barcodeScanTargetUrl",
    label: "Barcode Scan Target URL",
    description: "URL to load on QR scan. Use $code placeholder for the scanned value.",
    type: "url",
    category: "Other",
  },
];
